name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics.svg
          user: szqingt
          template: classic
          config_timezone: Asia/Shanghai
          committer_message: "chore: update metrics image"
          base: header, activity, metadata